FROM node:10
WORKDIR /smartbuy/app

COPY package*.json /smartbuy/app/

RUN npm install

RUN ng build 

COPY . /smartbuy/app/


EXPOSE 5015

CMD ["npm", "start"]


#
FROM nginx:alpine
COPY --from=node /smartbuy/app/dist/c360-app /user/share/nginx/html